---
- apt: name=python-setuptools
- apt: name=postgresql-server-dev-all
- apt: name=python-dev
- easy_install: name=psycopg2
- name: required packages
  action: apt pkg=$item state=present
  with_items:
    - apache2
    - software-properties-common
    - librmagick-ruby
    - ruby-rmagick
    - postgresql
    - libapache2-mod-passenger
  notify:
    - restart apache
    - restart psql


- name: enable passenger in apache2
  command: a2enmod passenger
  notify:
    - restart apache

- service: name=apparmor state=stopped

- name: create db
  sudo_user: postgres
  postgresql_db: db=${redmine_db} state=present
  notify:
    - restart psql

- name: create user for redmine db
  sudo_user: postgres
  postgresql_user: state=present name=${redmine_dbuser} password=${redmine_dbpass}
  notify:
    - restart psql

- name: redmine install
  action: apt pkg=$item state=present
  with_items:
    - redmine
    - redmine-pgsql
  notify:
    - restart apache


- name: install redmine database.yml
  template: src=../templates/database.yml dest=/etc/redmine/default/database.yml


- name: symlink redmine
  file: src=/usr/share/redmine/public  dest=/var/www/redmine state=link

- name: make schema
  command: rake db:migrate RAILS_ENV="production" chdir=/usr/share/redmine

- name: load default data
  command:  rake redmine:load_default_data REDMINE_LANG="en" RAILS_ENV="production" chdir=/usr/share/redmine

  ##XXX
- name: install redmine nginx.conf
  template: src=../templates/redmine.conf dest=/etc/apache2/sites-available/redmine.conf

- name: symlink to sites-enabled
  file: src=/etc/apache2/sites-available/redmine.conf dest=/etc/apache2/sites-enabled/redmine.conf state=link
  notify:
    - restart apache
